SELECT  x.NAME as NAME_X, y.NAME as NAME_Y, count(distinct x.CART_ID) as "장바구니 수"
FROM CART_PRODUCTS x JOIN CART_PRODUCTS y ON x.CART_ID = y.CART_ID
WHERE  x.NAME != y.NAME
GROUP BY x.CART_ID
ORDER BY x.NAME, y.NAME;
